### ISSUE TITLE
cannot truncate table in postgres

### ISSUE THREAD

**Issue by yitzchakl** [kennethreitz/records#106] opened 2017-06-25 10:23 UTC
Hi.

when trying to run a truncate statement on some table in postgres it does not affect the table, its even causes a lock on the table for read (select).
what could be the problem?

Thanks,
Yitzchak.

**Comment by szymonlipinski** [comment] 2017-09-07 09:31
This is the way postgres works. Postgres needs to get exclusive lock for the whole table. When there are some database connections, which are using that table, the exclusive lock cannot be acquired. So this connection with the truncate command just waits till the lock will be given.

**Comment by vlcinsky** [comment] 2018-04-26 21:59
As @szymonlipinski noted, this is caused by Postgresql and cannot be resolved in `records` package. Closing.

**Closed by vlcinsky** 2018-04-26 21:59 UTC
